[project]
name = "py-mu-pdf"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pymupdf>=1.26.4",
]

[dependency-groups]
dev = [
    "ipython>=9.5.0",
]
